"""Static ROS4HRI semantic-joint to CMU-bone rotation map.

Each wire DOF (GaitGenerator.JOINT_NAMES) rotates its target bones about a baked
bone-local axis, scaled per target so one DOF can spread over a chain. Axes are
measured from the contract renderer and mapped through each bone's neutral
skeleton-global rotation, signs baked to +1.0. Regenerated by
tests/peds/test_bone_map_parity.py when the skeleton or the contract rig changes.
Axes are measured at the rest pose, so shoulder yaw and twist blend approximately
under large flexion (exact for gait, where both stay 0).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BoneTarget:
    """One semantic joint's contribution to one CMU bone's local rotation."""

    bone: str  # CMU bone name (leaf of a token in the skeleton's joint_order)
    axis: tuple[float, float, float]  # unit rotation axis, in the bone's local rest frame
    sign: float  # +1.0 or -1.0, flips rotation direction (e.g. mirrored L/R bones)
    scale: float = 1.0  # share of the semantic angle applied to this bone


BONE_MAP: dict[str, tuple[BoneTarget, ...]] = {
    "r_waist": (  # torso roll (lateral lean), same spine spread as waist
        BoneTarget("LowerBack", (-0.1374, 0.0787, 0.9874), 1.0, 0.5),
        BoneTarget("Spine", (-0.1428, -0.0795, 0.9865), 1.0, 0.3),
        BoneTarget("Spine1", (-0.1502, -0.0054, 0.9886), 1.0, 0.2),
    ),
    "y_waist": (  # torso yaw (body torque), same spine spread as waist
        BoneTarget("LowerBack", (0.0181, 0.9969, -0.0770), 1.0, 0.5),
        BoneTarget("Spine", (-0.0187, 0.9968, 0.0776), 1.0, 0.3),
        BoneTarget("Spine1", (0.0655, 0.9977, 0.0154), 1.0, 0.2),
    ),
    "waist": (  # torso forward lean (spine flexion), spread over the spine chain
        BoneTarget("LowerBack", (0.9904, -0.0073, 0.1384), 1.0, 0.5),
        BoneTarget("Spine", (0.9896, 0.0074, 0.1439), 1.0, 0.3),
        BoneTarget("Spine1", (0.9865, -0.0670, 0.1495), 1.0, 0.2),
    ),
    "r_head": (BoneTarget("Head", (-0.1353, -0.0169, 0.9907), 1.0),),  # head roll (ear-to-shoulder tilt)
    "y_head": (  # head yaw (look left/right), neck twist plus head
        BoneTarget("Neck1", (-0.0186, 0.9373, 0.3481), 1.0, 0.6),
        BoneTarget("Head", (-0.0058, 0.9999, 0.0163), 1.0, 0.4),
    ),
    "p_head": (  # head pitch (nod up/down), neck plus head
        BoneTarget("Neck", (-0.9878, -0.0127, -0.1554), 1.0, 0.35),
        BoneTarget("Head", (-0.9908, -0.0036, -0.1354), 1.0, 0.65),
    ),
    "l_y_shoulder": (BoneTarget("LeftArm", (-0.1005, -0.9944, 0.0325), 1.0),),  # L arm azimuth about body-up
    "l_p_shoulder": (BoneTarget("LeftArm", (0.9498, -0.0861, 0.3008), 1.0),),  # L shoulder flexion, primary arm swing
    "l_r_shoulder": (BoneTarget("LeftArm", (0.1005, 0.9944, -0.0325), 1.0),),  # L arm twist about the limb axis
    "l_elbow": (BoneTarget("LeftForeArm", (0.9249, -0.1620, 0.3439), 1.0),),  # L elbow flexion
    "r_y_shoulder": (BoneTarget("RightArm", (0.0646, -0.9964, 0.0551), 1.0),),  # R arm azimuth about body-up
    "r_p_shoulder": (BoneTarget("RightArm", (0.8758, 0.0301, -0.4817), 1.0),),  # R shoulder flexion, primary arm swing
    "r_r_shoulder": (BoneTarget("RightArm", (-0.0646, 0.9964, -0.0551), 1.0),),  # R arm twist about the limb axis
    "r_elbow": (BoneTarget("RightForeArm", (0.8678, 0.0362, -0.4956), 1.0),),  # R elbow flexion
    "l_y_hip": (BoneTarget("LeftUpLeg", (0.1576, 0.9663, -0.2038), 1.0),),  # L hip yaw (internal/external rotation)
    "l_p_hip": (BoneTarget("LeftUpLeg", (0.1258, 0.1850, 0.9746), 1.0),),  # L hip abduction (leg out to the side)
    "l_r_hip": (BoneTarget("LeftUpLeg", (0.9795, -0.1792, -0.0924), 1.0),),  # L hip flexion, primary leg swing
    "l_knee": (BoneTarget("LeftLeg", (0.9797, -0.1270, -0.1550), 1.0),),  # L knee flexion
    "r_y_hip": (BoneTarget("RightUpLeg", (-0.0389, 0.9870, -0.1561), 1.0),),  # R hip yaw
    "r_p_hip": (BoneTarget("RightUpLeg", (0.0365, -0.1548, -0.9873), 1.0),),  # R hip abduction
    "r_r_hip": (BoneTarget("RightUpLeg", (0.9986, 0.0441, 0.0300), 1.0),),  # R hip flexion, primary leg swing
    "r_knee": (BoneTarget("RightLeg", (0.9986, 0.0312, 0.0418), 1.0),),  # R knee flexion
    "l_ankle": (BoneTarget("LeftFoot", (-0.9203, -0.3689, -0.1303), 1.0),),  # L ankle sagittal, positive dorsiflexion
    "r_ankle": (BoneTarget("RightFoot", (-0.9371, 0.3481, 0.0261), 1.0),),  # R ankle sagittal, positive dorsiflexion
}
